# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantlocation_loacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='catagory',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
