# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurantlocation_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='timestap',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
