# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20180618_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='files',
            field=models.FileField(default=django.utils.timezone.now, max_length=120, upload_to='profile_pic'),
            preserve_default=False,
        ),
    ]
