# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20180618_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='loacation',
            new_name='location',
        ),
    ]
