# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-20 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurantlocation_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='catagory',
            new_name='category',
        ),
    ]
