# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180625_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
